### ISSUE TITLE
Review comments

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guide-cloud-ibm#24]
- Since there is no code pane, the visual presentation feels at odds with the general multi-pane style.  See https://github.com/OpenLiberty/openliberty.io/issues/1177.

- Consider "What is Kubernetes?" and "Why use Kubernetes service in the cloud?" sub-sections under "What you'll learn" instead of a top-level section before "What you'll learn".

- For "Why use Kubernetes service in the cloud?", add a reference to DevOps e.g. work locally first and then push to cloud for further testing as part of DevOps so useful to understand how to deploy to a hosted Kubernetes service.

- The first paragraph under "Creating a Kubernetes cluster on IBM Cloud" feels abrupt and I was lost for a while thinking what do I need to do to create a Kubernetes cluster ... Should set it up better and transition it smoothly over to the following sections, which are the steps to setup a cluster.

- What's the thinking behind the section on deploying a new version of the system service? Should it be a top-level section?

- "Deploying to IBM Cloud Private":  I will reorganize the first 2 paragraphs to talk all about private cloud and on-premises deployments first and then indicate that ICP is the option for Kube on-prem from IBM.

- Can add the Istio Intro guide as one of the "Where to next?" guides too.

- The page-description, page-seo-title and page-seo-description need work.  The title too.  The current title is inconsistent with the Amazon EKS guide.  Have to get these right.

- Should have a placeholder issue to switch the link for the Docker guide mentioned to the new one under development.

@gkwan-ibm

**Comment by andrewdes** [comment]
> What's the thinking behind the section on deploying a new version of the system service? Should it be a top-level section?

The thought behind this section was to teach users how to redeploy a microservice after they've made changes to it (similar to the `Redeploy microservices`) section in the kube-intro guide. Looking at the guide, I think this section should be a top-level section. It will also keep it consistent with the guides we have out there that do something similar.

**Comment by yeekangc** [comment]
Thank you, @andrewdes.  That's good thinking.  I will call out the context further beyond what we have at the moment.  For example, you have made some changes, you want to re-deploy, here is how you can do it.

**Comment by evelinec** [comment]
@yeekangc can you review the changes for this issue and close when ready. Thanks.
