### ISSUE TITLE
Pre-Publishing Tests

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guide-cloud-ibm#33]
Pre-Publishing Tests

- [x] Read through the guide 
  - Check appearance (contents, headings, paragraphs, code snippets, outputs, links, hotspots) of the guide on the draft site
- [x] Follow the instruction in the guide to test that it is working
  - Clone the master branch
  - Use the `copy` buttons instead of typing 
- [x] Run `diff -r start/ finish/` 
- [x] Check that the release date on the readme.adoc is the publishing date
- [x] Platforms
   - Mac: end to end
  - Linux & Win: 
    - `mvn package`

**Comment by evelinec** [comment]
@MaiHameed can you update this task?

**Comment by evelinec** [comment]
As the update in scrum today, this task had been done. @MaiHameed pls keep your task updated with status.

**Comment by MaiHameed** [comment]
Completed a full end-to-end test running a clean Linux VM running Ubuntu 18.04.2.

**Comment by NimG98** [comment]
Completed end-to-end testing on Windows 10

**Comment by DannyS03** [comment]
Completed end-to-end testing on Mac

**Comment by evelinec** [comment]
Looks like this is completed. Closed.
