### ISSUE TITLE
Post-Publishing

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guide-cloud-ibm#36]
Post-Publishing Tests (Nimrah)
- [x] Check appearance (contents, headings, paragraphs, code snippets, outputs, links) of the guide on openliberty.io
- [x] Clone repo from master and do end to end

Other post-publishing tasks (to be done by the Admin Team) (Eveline)
- [x] Add description for the repo with link to guide's published website
- [x] Ensure automated test for PR and daily build using Travis, see [instruction](https://github.ibm.com/was-liberty/openliberty-guides-team/wiki/Automation-Tests-For-OpenLiberty-Guides#setup-travis-ci-tests-for-openliberty-guides) 
- [x] Enable pull creation notification on the repo for `was-lib-guides-alerts`, see [instruction](https://github.ibm.com/was-liberty/openliberty-guides-team/wiki/Automation-Tests-For-OpenLiberty-Guides#subscribing-static-guides-repositories-to-a-slack-channel)
- [x] Add the new guide's repo to the `OpenLiberty/guides-common` ZenHub board
- [x] (Optional) Send announcement to slack channel(s)
- [x] Consider SEO title and description for the guides
- [x] Enable `master` and `qa` branch lock down

**Comment by NimG98** [comment]
Issue with table in grey block:

The resource-group-name column overflows and interferes with the first column. And it kinda looks confusing as to where everything should be

On openliberty.io site (Mac, Safari):

<img width="968" alt="Screen Shot 2019-05-29 at 2 55 31 PM" src="https://user-images.githubusercontent.com/46586499/58583954-25229380-8223-11e9-9ff3-cf272c206da6.png">

On terminal:

<img width="968" alt="Screen Shot 2019-05-29 at 2 55 46 PM" src="https://user-images.githubusercontent.com/46586499/58583973-2fdd2880-8223-11e9-95f8-7d69a04e0a5f.png">

**Comment by NimG98** [comment]
Spelling error:

- [ ] ***substitue*** should be substitute

    `"This will be the hostname you ***substitue*** into commands later in this guide."`

**Comment by evelinec** [comment]
@andrewdes can you take a look at the above feedback? Thanks.

**Comment by andrewdes** [comment]
Yes I have addressed it here: https://github.com/OpenLiberty/guide-cloud-ibm/pull/46 and am waiting for review.

**Comment by evelinec** [comment]
@NimG98 are you good with the changes? Can we close this issue?

**Comment by NimG98** [comment]
I don't think we should close the issue yet, the changes are going through QA right now.

**Comment by DannyS03** [comment]
PR on QA

Issue still persists on Safari 
Fixed for Chrome and Firefox

![image](https://user-images.githubusercontent.com/25497083/58719648-380da300-839e-11e9-98d0-3e54d1544c2a.png)

![image](https://user-images.githubusercontent.com/25497083/58719702-55427180-839e-11e9-8cf8-f24aa869efb6.png)

**Comment by evelinec** [comment]
@NimG98 can we close this issue now?

**Comment by NimG98** [comment]
All other feedback has been addressed, and has been merged into master. 

The grey-box scrolling UI bug is being addressed as a separate issue (can be found here: https://github.com/OpenLiberty/openliberty.io/issues/1200)
