### ISSUE TITLE
Enable daily build to run in production

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guide-cloud-ibm#44]

**Comment by evelinec** [comment]
Verified that the `Continous Test: [cl190620190530-1901]` is running successfully. However, the travis job execution seems to have too much logs, the summary of the test did not get displayed. Pls investigate to see if any of the intermediate logs can be reduced.

**Comment by andrewdes** [comment]
Moved this to a separate issue: https://github.com/OpenLiberty/guide-cloud-ibm/issues/52. Closing this issue since the daily builds run successfully in production.
