### ISSUE TITLE
Warning in "Deploying new version of system microservice"

### ISSUE THREAD

**Issue by justineechen** [OpenLiberty/guide-cloud-ibm#54]
After deploying the second version of the system microservice and running 
`kubectl describe pod [pod-name]`
the following warning is shown:

```
Events:
  Type     Reason     Age                    From                     Message
  ----     ------     ----                   ----                     -------
  Normal   Scheduled  3m3s                   default-scheduler        Successfully assigned default/system-app-ibm-open-libe-7b58f846b4-qbfdd to 10.118.180.139
  Normal   Pulling    3m2s                   kubelet, 10.118.180.139  pulling image "us.icr.io/node-test/system:2.0-SNAPSHOT"
  Normal   Pulled     2m58s                  kubelet, 10.118.180.139  Successfully pulled image "us.icr.io/node-test/system:2.0-SNAPSHOT"
  Normal   Created    2m58s                  kubelet, 10.118.180.139  Created container
  Normal   Started    2m58s                  kubelet, 10.118.180.139  Started container
  Warning  Unhealthy  2m48s (x2 over 2m53s)  kubelet, 10.118.180.139  Readiness probe failed: Get http://172.30.158.13:9080/: dial tcp 172.30.158.13:9080: connect: connection refused
```

**Comment by TiagoF99** [comment]
- implemented inventory & system readiness/liveness checks and it did not fix anything
- followed https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/ as well as other online sources to try to configure the readinessprobe but it did not remove the warning message. 
- I believe that this error message does not affect the guide at all as all endpoints still work. The warning message just says that the container failed to start up at first but then restarted and was succesful which can be seen with the stuff above the warning. 
- we dont believe this is an issue.

**Comment by gkwan-ibm** [comment]
close based Tiago investigation on above
