### ISSUE TITLE
Peer Review - Mac

### ISSUE THREAD

**Issue by MaiHameed** [OpenLiberty/guide-cloud-ibm#76]
Peer Review: review to be done by a peer member. 

Functionality
---
- [ ] Check that the guide has working instructions and sample code
- [ ] Test the guide on 3 platforms: Mac, Win, Linux
- [x] If any URL visits, try them on different browsers: Firefox, Chrome, Safari
- [x] If any URL visits, try `curl` command where applicable 

Formatting & Presentation
---
- [x] Check the quality of code according to the best coding practices
    - [x] Ensure that command substitutions use the `$(cmd)` format and not ``` `cmd` ```
    - [x] Ensure that the console output of the integrated tests do not include the `[INFO]` tab
- [x] Check the quality and presentation of guide according to [Structure and Style Guideline](https://github.com/OpenLiberty/draft-guides-template/wiki/Guidelines-for-Structure-and-Styles)
- [x] Check the consistency of guide with template and other guides
- [ ] Examples with the right outcomes are provided
- [ ] Example with the wrong outcomes, if any, are provided
- [ ] Check that all licensing statements are properly stated in all files
- [x] Check that the `pom.xml`, `server.xml`, etc files are clean
- [x] Check that the directories are properly structured
- [x] Ensure that the guide is using the latest version of the `liberty-maven-plugin` or `liberty-gradle-plugin` where applicable
- [ ] Check that some of these `page-tags` are used in a guide: `MicroProfile, Maven, Docker, Kubernetes, Gradle, Java EE, Security, Cloud`. Only these tags are visible on the website. Latest list [here](https://github.com/OpenLiberty/openliberty.io/blob/master/src/main/content/_includes/visible-tags.liquid). 
- [ ] Check the `attribution` statement is accurate for the guide
- [ ] Verify the `travisTest.sh` script, if any, is accurate and consistent with other guides

Peer Testing: tests to be done by a peer member.

Guide’s contributor’s (if available, otherwise peer tester’s) responsibility: 
- [ ] Additional tests where applicable: 
    - [ ] Define test coverage and review with team (including guide contributor, if available)
    - [ ] Define detail test cases 
    - [ ] Consider corner cases targeting the specific guide
    - [ ] Consider different platform tests, ie, Mac, Windows, Linux
    - [ ] Consider corner cases UI tests
    - [ ] Consider testing URL on all browsers, ie, FF, Chrome, Safari
    - [ ] Consider testing the `curl` command for URL visits
- [ ] Consider building with both Maven and Gradle build tools 
- [ ] Testing with different IDEs, ie, Atom, Eclipse (Optional: VS.code, IntelliJ, Microclimate)
- [ ] Run Acrolinx Checker on draft (above 70 score approximately)
- [ ] Consider SEO title and description for the guides 
- [ ] Ensure automated test is enable, set up with Travis CI, and able to schedule tests 
- [ ] Run `diff -r start/ finish/` and there's no differences
- [ ] Ensure that the automation tests are able to run when PR is created

Peer Tester’s responsibility: 
- [x] Check the appearance of the guide on test site for the following items: 
    - [x] Table of contents 
    - [x] Headings
    - [x] Paragraphs
    - [x] code snippets
    - [x] outputs
    - [x] links
    - [x] hotspots 
- [ ] Test the guide end-to-end with working instruction and sample code
- [ ] Perform all the defined test cases 

---

## Additional Prerequisites
- Helm requires `tiller`. I got an error when running a `helm` command later on in the guide, however the Helm installation guide linked in this section only explains how to install `helm` and does not mention Tiller at all.

## Deploying your microservices
- Running the following command:
```
helm install system-app \
    --set image.repository=us.icr.io/guide-cloud/system \
    --set image.tag=1.0-SNAPSHOT \
    --set image.pullSecret=default-us-icr-io \
    --set service.name=system-service \
    --set service.port=9080 \
    --set service.targetPort=9080 \
    --set ssl.enabled=false \
    ibm-charts/ibm-open-liberty
```
results in an error: `Error: could not find tiller`

- Licence of `InventoryManager.java` in finish/start directories needs to be updated to `2020`
- Javadoc comments in the tests file should be removed for guide consistency.
- Should remove `// INSTRUCTION ..` comment from README

**Comment by k-rtik** [comment]
@MaiHameed I updated the guide to use Helm v3 which has breaking changes : it doesn't require Tiller anymore

**Comment by MaiHameed** [comment]
Helm issue fixed

## Tests
Getting errors when running the inventory tests from the start directory
```
[INFO] Running it.io.openliberty.guides.inventory.InventoryEndpointIT
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.349 s <<< FAILURE! - in it.io.openliberty.guides.inventory.InventoryEndpointIT
[ERROR] it.io.openliberty.guides.inventory.InventoryEndpointIT  Time elapsed: 0.349 s  <<< ERROR!
java.lang.NoClassDefFoundError: javax.xml.bind.JAXBException
	at it.io.openliberty.guides.inventory.InventoryEndpointIT.oneTimeSetup(InventoryEndpointIT.java:61)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at it.io.openliberty.guides.inventory.InventoryEndpointIT.oneTimeSetup(InventoryEndpointIT.java:61)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   InventoryEndpointIT.oneTimeSetup:61 » NoClassDefFound javax.xml.bind.JAXBExcep...
[INFO]
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
```

**Comment by MaiHameed** [comment]
All issues fixed and addressed.

**Comment by MaiHameed** [comment]
Tests issue fixed.
